# Generated by Django 5.2.1 on 2025-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_upload',
            field=models.FileField(default=1, upload_to='temp_uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
