# Generated by Django 5.2.1 on 2025-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_mediafile_file_upload_alter_mediafile_file_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_upload',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
